.github/workflows/audit-account.yml
.github/workflows/post-deploy-slack-notification.yml
.github/workflows/pr-notification.yml

Would you look at that...
N/A
---
---
---

Setup notification and audit workflows

---

services/ui-src/serverless.yml
src/runner.ts

Serverless compose gracefully exits with code 1 on error, thus not tripping the .error() catch in the runner. Add an extra catch for all non-success codes.
This was causing false successes in the deploy step, while logs of errors existed.
N/A
---
This action should have failed with an invalid ssm param: https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/actions/runs/9859930365
This action should succeed normally: https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/actions/runs/9860132356
The logging has been adjusted slightly since the first test.
---
---

Deploy Runner - handle Serverless Compose errors

---

README.md

Adding a single pane of glass to show  deploy status of each of our integration environments for HCBS. This helps more easily identify if one is red without having to go look through the deploy action in github
n/a
---
look at the readme on this bring 
n/a
---
---

Adding build badges to HCBS README

---

package.json
yarn.lock

Custom Lambdas are triggering warnings in security hub. These are used by the serverless framework as part of the deployment process. Upgrading to 3.39 should resolve it.
CMDCT-3901
---
Deployments succeed. Custom lambdas for cw-role || existing-s3 are on node 18, not 16.
Verified in seds:
---
---

[CMDCT-3901] Upgrade Serverless - Custom Lambda Runtime

---

services/ui-auth/libs/users.json
services/ui-src/src/types/users.ts
services/ui-src/src/utils/auth/UserProvider.tsx

Update the roles within hcbs to use the new formats provided by IDM/Okta team:
'mdct-hcbs-bor',
'mdct-hcbs-appr',
'mdct-hcbs-hd',
'mdct-hcbs-state-user',
'mdct-hcbs-internal-user'
CMDCT-3779
---
https://d1gh27jra9msrb.cloudfront.net/
Each user role should be able to still log in with test credentials. I have verified this with users in the users.json file.
---
---

[CMDCT-3779] update roles per idm config

---

.github/workflows/deploy.yml
.github/workflows/destroy.yml

This change *should* prevent destroy from firing while a deploy is running, but we won't know until this is merged, so YOLO
CMDCT-
---
---
---

Adjust concurrency group id

---

services/ui-src/src/components/layout/Timeout.tsx
services/ui-src/src/utils/auth/authLifecycle.test.tsx
services/ui-src/src/utils/auth/authLifecycle.tsx
services/ui-src/src/utils/other/time.ts

date-fns is a package we already had installed, and is a recommended swap for momentjs.
the moment package is a sub-dependency of serverless-bundle. we cannot remove it from yarn.lock, but hopefully this still resolves the issue.
References:
[Security issue](https://www.invicti.com/web-vulnerability-scanner/vulnerabilities/version-disclosure-momentjs/)
[MomentJS recommends using alternatives](https://momentjs.com/docs/#/-project-status/)
CMDCT-3911
---
- Modify the values for IDLE_WINDOW and PROMPT_AT in the src/constants.ts file to be shorter (change leading values to 1 and 0.5 or something)
- Run locally
- Let the app sit until the timeout hits
- Ensure the prompt shows up as expected
- Ensure the prompt still does the correct actions when you click on them
- Ensure if you don't do …

Remove and replace momentjs with date-fns

---

services/ui/serverless.yml

SecurityHub is mad because we don't use the 2022 new and shiny Origin Access Control rules for our cloudfront distro. Instead we are using Origin Access Identity, which is a slightly more complex pattern to do the same thing.
I am pretty sure the old CMS AWS accounts have this rule disabled, and HCBS is flagged because it is under the new account setup. Regardless, easy enough to clean up and remove a slightly more complicated config in favor of one that just sets up a single rule between two resources.
This just takes the bucket we host our UI in, and says it can only be accessed via the specific cloudfront distribution. No public access by navigating directly to the bucket.
CMDCT-3958
---
https://du8ioa447dep0.cloudfront.net/
Deployed link still works, you wouldn't be able to access the …

CMDCT-3958: Swap to OAC on UI Bucket

---

services/app-api/forms/qm.ts
services/app-api/handlers/reports/update.test.ts
services/app-api/handlers/reports/update.ts
services/app-api/serverless.yml
services/app-api/types/reports.ts
services/ui-src/src/components/fields/DateField.test.tsx
services/ui-src/src/components/fields/DateField.tsx
services/ui-src/src/components/fields/TextField.test.tsx
services/ui-src/src/components/fields/TextField.tsx
services/ui-src/src/components/report/Elements.tsx
services/ui-src/src/components/report/Page.test.tsx
services/ui-src/src/components/report/Page.tsx
services/ui-src/src/components/report/ReportPageWrapper.test.tsx
services/ui-src/src/components/report/ReportPageWrapper.tsx
services/ui-src/src/components/report/Sidebar.test.tsx
services/ui-src/src/components/report/Sidebar.tsx
services/ui-src/src/components/report/StatusTable.test.tsx
services/ui-src/src/components/report/StatusTable.tsx
services/ui-src/src/types/report.ts
services/ui-src/src/types/states.ts
services/ui-src/src/utils/api/requestMethods/report.test.ts
services/ui-src/src/utils/api/requestMethods/report.ts
services/ui-src/src/utils/state/management/reportState.test.ts
services/ui-src/src/utils/state/management/reportState.ts
services/ui-src/src/utils/state/useStore.ts

Introduce a light version of autosave and populate the modified form when revisiting the page.
- Merges the answers from the form back into the report, then submits.
- Only triggers that update onBlur, the typing in each field is a separate event that still updates the field.
- Each input object is taking its "formkey" (its path in the json from the page level), and applying "answer" itself. More complex inputs or input groups can follow the same pattern to declare their own field in the json, or structure.
- The report is loaded into react hook form to provide defaults. By virtue of these paths matching, it pre-populates without the hydration logic that is baked into MFP & MCR. 
- Moves PageMap to a dictionary of <Key, Number> where it just keeps track of the index. We can avoid tracking …

[Cmdct-3998] Save and Load Form

---

services/app-api/forms/qm.ts
services/app-api/types/reports.ts
services/ui-src/src/components/accordions/TemplateCardAccordion.tsx
services/ui-src/src/components/app/App.tsx
services/ui-src/src/components/layout/PageTemplate.tsx
services/ui-src/src/components/report/Elements.tsx
services/ui-src/src/components/report/MeasureTable.tsx
services/ui-src/src/components/report/Page.tsx
services/ui-src/src/components/report/ReportPageWrapper.tsx
services/ui-src/src/components/report/Sidebar.test.tsx
services/ui-src/src/components/report/Sidebar.tsx
services/ui-src/src/components/report/StatusTable.test.tsx
services/ui-src/src/components/report/StatusTable.tsx
services/ui-src/src/components/tables/Table.tsx
services/ui-src/src/components/tables/TableStatusIcon.tsx
services/ui-src/src/styles/index.scss
services/ui-src/src/styles/theme.ts
services/ui-src/src/types/report.ts

**1)** This PR is for fixing font sizing, padding and margin spacing for the report page layout. 
Also, the report page width has changed to the same width as MFP/MCR report page.
Examples:
**2)** There are also code for adding/fixing mobile view.
Previous mobile view
https://github.com/user-attachments/assets/5ff609d1-592d-425d-a90c-ad8248626cfa
Updated mobile view
https://github.com/user-attachments/assets/7357398e-9a19-4c61-a166-de6855e4ce56
**3)** Other Changes:
- Fixed spelling of statue to status 
- Fixed spelling of accordian to accordion
- The sidebar now has a slide transition animation
CMDCT-3996
---
Deploy Link: https://d1m9pfnv945hir.cloudfront.net/
1) Sign into HCBS, any user
2) Run through the app and make sure nothing is broken
3) To test mobile: shrink the width of your …

Layout & Mobile

---

services/app-api/handlers/reports/buildReport.ts
services/app-api/handlers/reports/update.ts
services/app-api/package.json
services/app-api/types/reports.ts
services/app-api/yarn.lock
services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/report/ReportPageWrapper.test.tsx
services/ui-src/src/types/report.ts
services/ui-src/src/utils/state/management/reportState.test.ts

Need an id? Thinking it might need to be unique? This is the PR for you.
For the actual id of our reports, we likely want an actual unique, non-composite string. Requirements still seem to be swinging back and forth about the uniqueness of reports and any limits to them. This for now will let us track them all independently and enforce any logic around uniqueness in the business logic.
CMDCT-4010
---
https://d1tvt7ld2qwuw2.cloudfront.net/
- State User
- Create Report
- New Report URL has Unique ID
- Report appears in table of available reports.
---
---

[Cmdct-4010] - Update Report ID

---

services/app-api/handlers/reports/buildReport.test.ts
services/app-api/handlers/reports/buildReport.ts
services/app-api/handlers/reports/create.ts
services/app-api/handlers/reports/update.ts
services/app-api/types/reports.ts
services/app-api/types/types.ts
services/app-api/utils/authentication.ts
services/app-api/utils/tests/authentication.test.ts
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx

* Ensure that the `lastEditedBy` field is populated on report creation & report update
* Rename the `user.full_name` property to `user.fullName`; just because the JWT uses `snake_case` doesn't mean we shouldn't use our standard `camelCase` for properties we control
* Embolden the report name on the dashboard
* Give the report name on the dashboard more space
CMDCT-3950
---
1. Log in as a state user
2. Create a report
3. Look at your user's full name on the report dashboard.
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
- ~[ ] I have updated relevant documentation, if necessary~

Dashboard details

---

services/ui-src/src/components/fields/RadioField.test.tsx
services/ui-src/src/components/fields/RadioField.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/report/Elements.tsx
services/ui-src/src/components/report/Page.tsx
services/ui-src/src/types/report.ts

Pulling in the radio element from MFP and merging it with HCBS code
CMDCT-4094
---
Deploy Link: https://d3vavmjkf7yx45.cloudfront.net/
2) Click [**Enter HCBS QM online**]
3) Create a report by clicking [**Start Quality Measures Report**] and fill out the form. 
- This page is being removed so I didn't bother updating the radio buttons here.
4) Once the report is created, it should show up on the dashboard, click [**Edit**]
5) Go to the [**Required Measure Results**] section, select the [**Edit**] button on the page
6) There should be a radio button on the page:
7) Click any radio button and it should trigger the autosave.
8) Leave the page and come back, the value you selected should still be there
---
---
_convert to a different template: [test → …

Radio Element

---

services/ui-src/src/components/layout/HomePage.tsx

This PR adds the code for displaying the banner to the home page for any state user and non state user.
CMDCT-4091
---
Deploy Link: https://d19jc7bal1zoty.cloudfront.net/
_Generate a banner to be displayed_
Follow the steps [here](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/58) to generate a banner. Make sure the start and end date encompasses the current date. 
_View the Banner_
1) Once the banner is generated, if you go back to the homepage of the admin user, you should see it.
2) Sign out and sign back in as a state user, any user. Once logged in, you should see the banner at the top of the page.
---
---

Display Banners

---

services/app-api/forms/qm.ts
services/app-api/handlers/reports/buildReport.test.ts
services/app-api/handlers/reports/buildReport.ts
services/app-api/handlers/reports/create.ts
services/app-api/types/reports.ts
services/ui-src/src/components/pages/CreateReportOptions/CreateReportOptions.tsx
services/ui-src/src/types/report.ts
services/ui-src/src/utils/api/requestMethods/report.test.ts
services/ui-src/src/utils/api/requestMethods/report.ts

This is the first PR in the Create Report by Name stack. This PR sets up the backend so that a report name can be a part of createReport(). I'm restructuring FormOptions -> ReportOptions, which will for now contain one parameter "name". This is where the user-inputted name will be written to and then retrieved.
CMDCT-4058
---
cloudfront link: https://d14t2we268cnpm.cloudfront.net/
Make sure the app runs normally, no UI changes yet
---
---

1/x Create Report by Name - Setup backend

---

services/app-api/forms/cmit.ts
services/app-api/forms/qm.ts
services/app-api/handlers/reports/buildReport.ts
services/app-api/types/reports.ts
services/app-api/utils/constants.ts
services/ui-src/src/cmit.ts
services/ui-src/src/components/fields/RadioField.test.tsx
services/ui-src/src/components/fields/RadioField.tsx
services/ui-src/src/components/report/MeasureTable.test.tsx
services/ui-src/src/components/report/MeasureTable.tsx
services/ui-src/src/components/report/Page.test.tsx
services/ui-src/src/components/report/Page.tsx
services/ui-src/src/components/report/QualityMeasureTable.tsx
services/ui-src/src/components/report/ReportPageWrapper.test.tsx
services/ui-src/src/types/report.ts
services/ui-src/src/types/states.ts
services/ui-src/src/utils/state/management/reportState.test.ts
services/ui-src/src/utils/state/useStore.ts
services/ui-src/src/utils/testing/setupJest.tsx

This PR builds out LTSS-1 measure overview page. The content of what's suppose to be on this page is written in the jira ticket, the figma is just for a general idea of what the page might look like,
I also expanded the radio button to have children elements underneath. 
**Note**
1) Children textboxes of the radio button currently does not save any data. Will address in a separate PR.
2) The quality measure table [Edit] buttons do not go anywhere yet. Also will address in a separate PR. 
CMDCT-4139
---
2) Create a QM report
3) On the sidebar menu, select [**Required Measure Results**]. You should see a row for CMIT # 960.
- The generation for this table is covered by another ticket.
4) Click [**Edit**] and you be taken to the  LTSS-1 measure overview …

QMS - LTSS-1 - Measure Overview Page

---

services/app-api/forms/qm.ts
services/app-api/types/reports.ts
services/ui-src/src/components/report/MeasureTable.tsx

Added a new optional measures page (replaced the stratified measures page) and added in optional measures.
CMDCT-4137
---
https://d3653emqila4aa.cloudfront.net/
1. Log in as any user
2. Go to QM report and start a new one
3. Go to Optional Measure Results tab and make sure there's a list of measures there that matches the screenshot above

CMDCT-4137: adding optional measures page with new optional measures

---

services/app-api/forms/cmit.ts
services/app-api/forms/qm.ts
services/ui-src/src/cmit.ts

This PR adds the content for the LTSS-3 measure.
As of now, thanks to the all the great work done in setting up [LTSS-1](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/66), I only had to update the qm.ts and cmit.ts files.
> I propose, holding off on the edit button going to a blank page at least until the routing by page id PR is merged in, so there's consistency with how we're routing.
- Clicking the edit button should take you to that measure's delivery method page.
Notes from LTSS-1
1. Children textboxes of the radio button currently does not save any data. Address in a separate PR.
2. The quality measure table [Edit] buttons do not go anywhere yet. Address in a separate PR.
CMDCT-4143
---
1. Sign into HCBS, any state user
2. Create a QM report
3. On the sidebar menu, select …

LTSS-3 Measure Overview Page

---

services/app-api/forms/cmit.ts
services/app-api/forms/qm.ts
services/ui-src/src/cmit.ts

This PR adds the content for the LTSS-2 measure overview page. The content of what's suppose to be on this page is written in the jira ticket, the figma is just for a general idea of what the page might look like
Notes from LTSS-3:
"I propose, holding off on the edit button going to a blank page at least until the routing by page id PR is merged in, so there's consistency with how we're routing."
Notes from LTSS-1:
"Children textboxes of the radio button currently does not save any data. Address in a separate PR."
"The quality measure table [Edit] buttons do not go anywhere yet. Address in a separate PR."
CMDCT-4141
---
Sign into HCBS, any state user: https://d23qdxt8dq336v.cloudfront.net/
Create a QM report
On the sidebar menu, select [Required Measure Results]. You should see a row for …

QMS - LTSS-2 - Measure Overview Page

---

services/ui-src/src/utils/auth/UserProvider.tsx

Garrett and I have been working on the Amplify logout issues and we think its because the call get cancelled due to the redirect happening. Amplifys signout seems to handle this redirect just fine with out it, so we're hoping by just removing that line the logout issue will be fixed!
---
Sign into HCBS with IDM
Click logout in the application
Wait until you're in the IDM site and log out of that too
Navigate to mdcthcbsdev.cms.gov
Click sign into HCBS with IDM
If you were taken to the login screen to input your username and password, it worked!
If you were taken directly into the application, it did not work :(

Amplify V6: Remove window.location call in logout to stop cancelling cognito call

---

services/ui-src/src/components/modals/AddEditReportModal.test.tsx
services/ui-src/src/components/modals/AddEditReportModal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx

Pretty simple PR to allow users to edit report name from the dashboard table. I went pretty simple here since there is just one field. I did not use any useForm magic so let me know if that is more appropriate here.
CMDCT-4185
---
https://d2nvrsyhsh8gv1.cloudfront.net/
Test as state user:
1. Log in as any state user
2. Navigate to report table
3. You should see an edit button next to every report. Click on the edit button and you should see the edit modal
4. it should say "Edit Quality Measure Set Report" and the button should say "Save"
5. The text box should be populated with the current name. Change the name and hit save and the row should update with the name you just changed to
6. Click on the edit button again and the name in the text field should reflect the current name
7. hit …

CMDCT-4185: adding edit button to dashboard table rows so that user can edit report name

---

services/app-api/forms/qm.ts

Language updates to following questions:
- Replace `the LTSS` with `this`
- **OLD:** "Which delivery systems were used to report _**the LTSS**_ measure?"
- **NEW:** "Which delivery systems were used to report _**this**_ measure?"
- Options for delivery system question updated with:
- Replace `Free-For-Service` with `Fee-For-Service (FFS)`
- Replace `Managed Care` with `Managed Long-Term Services and Supports (MLTSS)`
- Replace `Both` with `Both FFS and MLTSS (separate)`
- Replace `deviate` with `follow`
- **OLD:** ""Did you _**deviate**_ from the [reportYear] Technical Specifications?"
- **NEW:** "Did you _**follow**_ the [reportYear] Technical Specifications?"
- Replace `deviation` with `variance`
- **OLD:** "Please explain the _**deviation**_."
- **NEW:** "Please explain the …

[HCBS] Overview Page Language/Functionality Change

---

services/app-api/forms/qms.ts
services/ui-src/src/components/report/Page.test.tsx
services/ui-src/src/components/report/Page.tsx
services/ui-src/src/components/report/QualityMeasureTable.test.tsx
services/ui-src/src/components/report/QualityMeasureTable.tsx

At the bottom of each measure page is a table of delivery systems, with an Edit button for each row. But users are only required to report on the delivery system(s) they indicated they would report on, in a prior question. This pull request wires up these buttons' enabled/disabled states to that prior question.
In order to make this happen, I added a field called `formKey` to the delivery system selection radio button. Most inputs will have an auto-generated name like `"elements.7"`; these radio buttons will now have fixed names. Then I can query React Hook Form by the appropriate name to get the selected delivery system instantly (that is, without waiting for the report to update in the store).
I also changed the values of the radio buttons. Whereas previously we had …

Disable delivery system edit buttons, unless selected

---

run
services/app-api/serverless.yml
services/ui-auth/handlers/createUsers.js
services/ui-auth/package.json
services/ui-src/serverless.yml
services/ui/serverless.yml

There are a couple issues that came up related to the HCBS implementation of v4 so this is a mop up of outstanding problems.
CMDCT-4254
---
You can log into the application here:
https://d32y65zs9733uw.cloudfront.net/
NA
---
---

CMDCT-4254 - minor tweaks to serverless v4 implementation

---

services/app-api/forms/qms.ts

General Info page has been updated, these changes reflect the new design
CMDCT-4235
---
1. Login, create report, navigate to general info page. Should now look like this:
For a more detailed view of new design, here is the Figma link: https://www.figma.com/design/B8IEoYKQ7DuQyx5nStls8F/HCBS?node-id=357-10299&t=eUWseNW7cfV1Xvla-0
---
---

QMS - Update General Information Page

---

services/ui-src/src/components/report/ReportPageWrapper.tsx

This PR should fix the autosave refresh bug without breaking anything else.
N/A
---
To verify the bug is fixed:
1. Create a new report
2. Navigate to a page with more than one text input
3. Enter a value in one of the text inputs
4. Blur that field - which will trigger an autosave
5. Refresh the browser window
6. Enter a value in a different text input
7. Blur that field - which will trigger another autosave
8. Refresh the browser window
9. Note that both inputs still contain your values
Also:
1. idk, try a bunch of form... stuff. It should all work good.
n/a
---

Adjust useForm to more gracefully handle page refreshes

---

services/ui-src/src/components/export/ExportedReportBanner.tsx

Copied from MCR
- Add styling condition to export page header such that it only remains sticky at zooms below ~200%
- (using mobile & tablet sizing as condition)
Applies to all export pages, regardless of report type
This prevents the majority of the page from being covered by the banner at high zoom
CMDCT-4297 bonus
---
- Log in as a state user
- Create any report where you can view a PDF (export components)
- Go to Review & Submit page and open the PDF
- At desktop width scroll up and down
- Zoom in (`Cmd` + `+`) and test at various sizes
- Banner should become fixed to top of page at around 200% zoom
This just happens to be the functionality with mobile & tablet as the condition. We may be able to tweak further if needed, but this meets the requirements of the ticket and I think is a …

Make export page header static at 200+ zoom

---

services/ui-src/src/components/report/QualityMeasureTable.test.tsx
services/ui-src/src/components/report/QualityMeasureTable.tsx
services/ui-src/src/utils/state/hooks/useLiveElement.ts

React Hook Form and our store are enemies some days, but today we make them friends.
The QM component needs to update when radio buttons are clicked and be informed.
React Hook form:
- Hands off its updates on change successfully but sometimes has an empty initial state for useWatch()
- Our store always has the correct initial state, but only updates on blur actions. We need the info on a click.
This custom hook merges those two together, given an elementId on the current page. It is a little chattier than normal, and doesn't make sense everywhere, but it does make sense for QM tables.
N/A
---
https://d1pa8viu70th2x.cloudfront.net/
- Login as state user
- Go to a report measure page
- Fill out reporting type, it should live update
- Refresh, the Edit link should still be highlighted
- …

QM Table: State vs Form fix

---

services/ui-src/src/components/fields/TextAreaField.test.tsx
services/ui-src/src/components/fields/TextAreaField.tsx

I fixed the error propagation display in TextField a long time ago but never made the change for TextAreaField. This is so react hook form errors can be propagated down and grabbed correctly by TextAreaField. 
CMDCT-4193, CMDCT-4189
---
1. Log in as any user and create a report
2. Go to any of the required measures table and click into one to edit. Start filling out the form and try to get some children textboxes to pop up. notice if you blur the children without entering anything, you will get "A response is required" error. Type something in and it will go away

[NO TICKET]: fix issue where form errors were not getting displayed correctly for text area field

---

services/app-api/forms/defaultMeasures.ts

3 tiny fixes: 
- removed `MeasureDetails` from FFS as it was rendering an error page due to not finding cmitInfo and per [Figma](https://www.figma.com/design/B8IEoYKQ7DuQyx5nStls8F/HCBS?node-id=2215-8436&p=f&t=64ppKFGYcGyniMbu-0), these pages do not have this section at the top
- corrected FFS page to return to LTSS-1 as LTSS-1960 was leading to an error page.
- updated header and subheader and order of information to match Figma.
n/a
---
**Deploy Link:** https://d2mccnewlhkt1o.cloudfront.net/
1. Step in to Measure LTSS-1 measure.
2. Select Delivery Method: `FFS` at the bottom
3. Click on `Return to Measure Information` link and it should go back to LTSS-1
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | _[val → …

LTSS-FFS Delivery Method Page Fixes

---

services/app-api/forms/2026/measureOptions.ts
services/app-api/forms/2026/measureTemplates.ts
services/app-api/types/reports.ts
services/app-api/utils/reportValidation.ts
services/ui-src/src/components/report/Elements.tsx
services/ui-src/src/components/report/Page.test.tsx
services/ui-src/src/components/report/Page.tsx
services/ui-src/src/components/report/ReportPageWrapper.test.tsx
services/ui-src/src/styles/theme.ts
services/ui-src/src/types/report.ts
services/ui-src/src/utils/state/management/reportState.test.ts
services/ui-src/src/utils/testing/setupJest.tsx

CMDCT-4140
---
cloudfront: https://d3p0xu9i7j4ko8.cloudfront.net/
This page shows up when we choose to edit a delivery method. Navigate to page, and ensure that the UI looks correct (some caveats, see below).
Depending on whether you choose FFS or MLTSS, you should see the correct corresponding headers (Fee for Service Measure results or Managed Care Measure Results)
There's a few sections to make sure are visible: 
- Performance Rate: Assessment of Core Elements
- Performance Rate: Assessment of Supplemental Elements
- Exclusion Rate: Participant Count Not Be Contacted
- Exclusion Rate: Participant Refused Assessment
There should be a numerator, denominator, and rate field for each section. 
There should also be a Measure Stratification section with a radio button
UI caveats:
1. We are …

[HCBS] - QMS - LTSS-1 - Measure Details Page

---

services/ui-src/src/utils/testing/commonTests.tsx

Add WCAG 2.1 AA and WCAG 2.2 AA [rules to axe-core](https://www.deque.com/axe/core-documentation/api-documentation/#:~:text=the%20analysis%20again.-,axe-core%20tags,-Each%20rule%20in).
CMDCT-4382
---
Run UI Jest tests. They all should pass.
You can check which rules are being run if you place this console log close to where violation `results` are checked:
```JavaScript
console.log(results.toolOptions.runOnly?.values || "no rules");
```
---

CMDCT-4382 Add WCAG 2.1 AA and 2.2 AA rules

---

services/ui-src/src/components/fields/DropdownField.tsx

The dropdown within the create modal page worked sometimes. This sometimes was enough to block my other work.
The CMSDS dropdown component is wired up to emit its output onBlur and onChange. OnChange appears to behave, but the onBlur behavior for the event.target.value never contains the content of the update. InnerText or OuterText appear to behave correctly based on experimentation -- I couldn't find discussion around this.
Updated the call and added a comment for the future confused souls affected by design library changes.
The empty value was then cast to a Number(), which resulted in 0. Api requests were being sent for year 0.
CMDCT-4418
---
Go to the create report model and try to mess around in a couple ways.
- Clicking through the dropdown should allow a submission.
- Creating a …

[CMDCT-4418] Dropdown not working all the time

---

services/ui-src/src/components/fields/ReportingRadioField.tsx
services/ui-src/src/components/report/MeasureClearModal.tsx
services/ui-src/src/components/report/MeasureDetails.test.tsx
services/ui-src/src/components/report/MeasureDetails.tsx
services/ui-src/src/components/report/MeasureFooter.test.tsx
services/ui-src/src/components/report/MeasureFooter.tsx
services/ui-src/src/components/report/MeasureTable.tsx
services/ui-src/src/components/report/QualityMeasureTable.test.tsx
services/ui-src/src/components/report/QualityMeasureTable.tsx
services/ui-src/src/components/report/ReportPageWrapper.test.tsx
services/ui-src/src/components/report/ReportPageWrapper.tsx
services/ui-src/src/types/states.ts
services/ui-src/src/utils/state/management/reportState.test.ts
services/ui-src/src/utils/state/management/reportState.ts
services/ui-src/src/utils/state/selectors.ts
services/ui-src/src/utils/state/useStore.ts
services/ui-src/src/utils/testing/setupJest.tsx

Second attempt at running this through.
- Adds a selector for getting the current page, removes the repeated querying against selected pages
- Splits the save report action to its own action. This allows the synchronous part of the ui changes to run through just fine, then handle any api requests and errors. This unblocks any rendering nonsense where an action overwrites the state of the report after the api call goes through. If we do that, it should be deliberate.
- Threads errors from api calls into the state. There will be a future story to deal with the rendering, I have tested it local by rendering the error message into the action bar as a proof of concept, but no real behavior for now.
- *Disables UI Validation that is currently broken in main*. It is preventing autosave.
- …

Store sync: Round 2

---

services/ui-src/src/components/fields/DropdownField.tsx
services/ui-src/src/components/fields/RadioField.tsx
services/ui-src/src/components/fields/ReportingRadioField.tsx
services/ui-src/src/components/fields/TextField.test.tsx
services/ui-src/src/components/fields/TextField.tsx
services/ui-src/src/components/report/ReportPageWrapper.tsx
services/ui-src/src/types/states.ts
services/ui-src/src/utils/state/management/reportState.test.ts
services/ui-src/src/utils/state/management/reportState.ts
services/ui-src/src/utils/state/useStore.ts

With validation enabled, react hook form was requiring the entire page to be filled out before saving any answers. This PR addreses those lifecycle behaviors in a few ways. The end result is that you should be able to interact with the report on the first page, or a required measure page, and fill out partial info. Putting one answer in error should still allow you to save.
What changed?
- An error handler was added in ReportPageWrapper, that just takes those same results, and any errors, and passes them off to the normal setAnswers, before calling the save.
- If the error array is provided to this function, it will remove any answers with error messages from the store update, and save.
- The logic here is somewhat similar to the mergeAnswers, but a little more nuanced. We look to see …

React Hook Form Error Lifecycle

---

services/app-api/utils/sanitize.ts
services/app-api/utils/tests/sanitize.test.ts

Pull in the prior fix to MCR & MFP DOMPurify rules: https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/12000
Copying @benmartin-coforma's and @karla-vm's work
N/A
---
Unit tests should just about prove it, 
Otherwise, manually take the steps to inject html in the admin banner
---
---

Update dompurify with strict rules

---

deployment/constructs/waf.ts
deployment/stacks/api.ts
deployment/stacks/ui-auth.ts
deployment/stacks/ui.ts

WAF not able to hook up to Cloudwatch
Watch here for updates:
https://jiraent.cms.gov/plugins/servlet/desk/portal/22/CLDSPT-84507
In the meantime we are comment out that part for ephemeral branches
CMDCT-4506
---
Deploy works :)
---
---

CMDCT-4506 turn off waf logging for ephemeral branches for the time being

---

services/ui-src/src/components/rates/types/NDREnhanced.tsx

NDR Enhanced was not saving calculated info all the time, it was writing back the version of the info without new calculations.
CMDCT-4513
---
https://d1u6sa9lkiunbl.cloudfront.net/
- Go to LTSS-1, FFS-1
- Edit the rates
- The page should be completable without weirdness
- Refreshing should persist all data
---
---

[CMDCT-4513] NDR enhanced fix

---

services/app-api/forms/2026/elements.ts
services/app-api/types/reports.ts
services/app-api/utils/reportValidation.ts
services/ui-src/src/components/report/Elements.tsx
services/ui-src/src/components/report/MeasureFooter.test.tsx
services/ui-src/src/components/report/MeasureFooter.tsx
services/ui-src/src/types/report.ts
services/ui-src/src/utils/other/routing.ts
services/ui-src/src/utils/validation/reportValidation.test.ts

This PR changes the action of the [Previous] button in the measure footer. If the measure is the parent, the code will figure out the return. if it's a measure section, it was use the data entered in measureTemplates.ts.
https://github.com/user-attachments/assets/b0dabffa-cafa-4d42-a0c5-083c89d77336
CMDCT-4514
---
Deploy Link: https://d36ma4f5kxbyc2.cloudfront.net/
2) Create a QMS report
3) In Required Measures Results section, click [Substitute measure] link on LTSS-1. Change it to FASI-1.
4) Enter FASI-1, and scroll down, press the [Previous] button it should take you back to the Require Measures Results page
5) Go to the Optional Measure Results section
6) Find LTSS-1, and repeat the same action as FASI-1
7) When you click the [Previous] button, it …

Previous buttons sometimes go to the wrong page

---

services/app-api/forms/2026/elements.ts

Code climate and tools don't detect anomalies like duplicate properties until it's pushed to main and it see both from different PR's. This PR removes the additional `required: true,` from elements.ts
N/A
---
Tests pass

Hot fix: dupe property

---

services/ui-src/src/utils/state/reportLogic/reportActions.ts

There was a bug in the substitute modal where if you select no and click the buttons, the modal wouldn't do anything. This fixes it.
CMDCT-4548
---
Deploy Link: https://d22bne4hrcvfls.cloudfront.net/
2) Create a QMS report
3) Go to required measure results
4) Open the substitute modal. Click around to make sure all the buttons and options work
---
---

Substitute Measure Cancel Button Stalls

---

services/app-api/forms/2026/elements.ts
services/app-api/types/reports.ts
services/app-api/utils/reportValidation.ts
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/types/report.ts

This PR will tackle the issues of the complete button in a measure being enabled when the child field of a radio field is open. A simple fix, the child field needed to have the required key as part of it's template data.
https://github.com/user-attachments/assets/4109c64a-1170-46ae-8ee5-80b059965016
Also added a min and max width for the report dashboard title.
**Known Issue**
After entering the text, you can't seem to clear it from the children textbox. we're still working on what to do with that situation so you can ignore that.
CMDCT-4552
CMDCT-4547
---
Deploy Link: https://d19uyho4lexobc.cloudfront.net/
2) Create a new QMS report
3) Click [Required Measure Results] in the side navigation bar
4) Select [Edit] for LTSS-1 in the table
5) Fill out LTSS-1 …

Child Textfield error not preventing Completion

---

services/ui-src/src/components/rates/calculations.tsx
services/ui-src/src/components/rates/types/Fields.test.tsx
services/ui-src/src/components/rates/types/Fields.tsx
services/ui-src/src/components/rates/types/NDR.test.tsx
services/ui-src/src/components/rates/types/NDR.tsx
services/ui-src/src/components/rates/types/NDREnhanced.test.tsx
services/ui-src/src/components/rates/types/NDREnhanced.tsx
services/ui-src/src/components/rates/types/NDRFields.test.tsx
services/ui-src/src/components/rates/types/NDRFields.tsx
services/ui-src/src/components/report/PerformanceRate.tsx

**Task**
1. Denominator field should not allow for alpha characters
- We actually do have a check for the values being inputted into the fields, the issue was due to the default value being `undefined`. Because there was no value, the input would take any value and display it, so all we needed was to add a check that if it's undefined, default to an empty string. i.e.`value={value?.denominator ?? ""}`
2. After Submission, should be read only
- The rates textfields are not using the same textfields as the rest of the forms so they needed to have the code manually added for view only mode. It should now have a check like the rest of the application.
3. Updated Precision to reflect products limit for precision
- I changed the precision of the field back to decimals as we don't indicate them …

Performance Rate Input Behaviors

---

services/app-api/forms/2026/elements.ts
services/ui-src/src/components/rates/types/Fields.tsx
services/ui-src/src/utils/state/reportLogic/completeness.ts

This PR fixes the bug where complete section was showing up even though the answer for the "required" performance Target question was left blank.
Alternate option for the logic is: 
Looks cleaner but not sure if as readable. Curious what thoughts are:
```
if (
[uniqueRate.rate, uniqueRate.performanceTarget].some(
(uniqueRateValue) => uniqueRateValue === undefined || uniqueRateValue === ""
)
) {
return false;
}
```
CMDCT-4554
---
**Deploy link:** https://d13wce1kd9m1xw.cloudfront.net/
1. Sign into HCBS, any state user.
2. Create a new QMS report, say yes to the POM measures to check those too.
3. Go to any measure and confirm that if you leave the answer blank for the question: "What is the 2028 state performance target for this assessment?", that the complete button stays disabled. To …

[HCBS] State Performance Target Question Required

---

services/app-api/forms/2026/elements.ts
services/ui-src/src/components/app/AppRoutes.tsx
services/ui-src/src/components/fields/RadioField.test.tsx
services/ui-src/src/components/fields/RadioField.tsx
services/ui-src/src/components/fields/ReportingRadioField.test.tsx
services/ui-src/src/components/fields/ReportingRadioField.tsx
services/ui-src/src/components/fields/TextAreaField.test.tsx
services/ui-src/src/components/fields/TextAreaField.tsx
services/ui-src/src/components/fields/TextField.test.tsx
services/ui-src/src/components/fields/TextField.tsx
services/ui-src/src/components/report/MeasureFooter.tsx
services/ui-src/src/components/report/MeasureTable.tsx
services/ui-src/src/components/report/ReportAutosaveProvider.test.tsx
services/ui-src/src/components/report/ReportAutosaveProvider.tsx
services/ui-src/src/components/report/ReportPageWrapper.tsx
services/ui-src/src/types/states.ts
services/ui-src/src/utils/state/hooks/useElementIsHidden.ts
services/ui-src/src/utils/state/reportLogic/completeness.ts
services/ui-src/src/utils/state/reportLogic/reportActions.test.ts
services/ui-src/src/utils/state/reportLogic/reportActions.ts
services/ui-src/src/utils/state/reportLogic/reset.ts
services/ui-src/src/utils/state/useStore.ts
services/ui-src/src/utils/testing/setupJest.tsx

Addresses a few behaviors around the reporting radio button
1. When refreshing the page, hidden elements continue to be hidden
2. When toggling the yes/no, data in the measure is properly cleared
3. Other edge cases where saveReport was being managed were folded into the autosave provider, so they would never go rogue and overwrite each other.
Points 2 and 3 above were addresed by introducing an Autosave Provider, which moves the recent debounce in ReportPageWrapper up a level to a shared function. Now any time an action gets taken, that can be called and after 3 seconds of debounciness, the most recent version of any of these changes gets sent to be saved, whether it be text field changes, clearing measures, or completing them.
CMDCT-4512
---
https://d1m5rzw7wglmjj.cloudfront.net/
- …

[Cmdct-4512] Refresh hidden elements + Autosave Tweaks

---

services/ui-src/src/components/report/MeasureTable.test.tsx
services/ui-src/src/components/report/MeasureTable.tsx

After a report is submitted, it cannot be changed. One type of change that should be disallowed is the substitution of Optional Measures for Required ones. And now, with this PR, that _is_ disallowed! :tada:
Here is a screenshot showcasing the lack of "Substitute measure" buttons, within a submitted report:
CMDCT-4601
---
https://dgftiobu9dks4.cloudfront.net/
1. Create a report and fill it out
2. Observe that, when viewing the Required Measures page, each measure has a Substitute button
3. Submit the report
4. Observe that the Substitute button is gone
5. Unlock the report
6. Observe that the Substitute button is back
n/a
---
- ~[ ] I have updated relevant documentation, if necessary~

Hide the "Substitute Measure" button in submitted reports

---

services/ui-src/src/components/cards/ReportIntroCardActions.tsx
services/ui-src/src/utils/state/reportLogic/completeness.test.ts
services/ui-src/src/utils/state/reportLogic/completeness.ts

[Same issue as this PR](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/212) but with NDR Field rate calcs. The solution is to also see if performanceTarget or rates is "".
https://github.com/user-attachments/assets/014e5493-fbc3-413a-b908-7339546653ad
Also in this pr is a styling fix, I moved the button back to the right:
**Why does the solution require a cast?**
`(uniqueRate.rate as number | string) === ""`
So typescript is working correctly, as we have set rate to be a number and a number only. The issue is that for user experience, we have to be able to have an empty textbox and an undefined was not enough. An undefined causes the input to not fire our onchange/onblur correctly but we didn't want to allow it to take strings as we only wanted numbers to be save so we have this …

NDR Field Bug Fix

---

services/ui-src/src/components/fields/DateField.test.tsx
services/ui-src/src/components/fields/DateField.tsx
services/ui-src/src/components/fields/RadioField.tsx
services/ui-src/src/components/fields/TextAreaField.test.tsx
services/ui-src/src/components/fields/TextAreaField.tsx
services/ui-src/src/components/fields/TextField.test.tsx
services/ui-src/src/components/fields/TextField.tsx
services/ui-src/src/components/rates/types/Fields.tsx
services/ui-src/src/components/rates/types/NDR.tsx
services/ui-src/src/components/rates/types/NDREnhanced.tsx
services/ui-src/src/components/rates/types/NDRFields.tsx
services/ui-src/src/components/report/MeasureFooter.tsx
services/ui-src/src/components/report/StatusTable.tsx

Tabbing through radios was having a weird effect when you skipped right past. This was due to removing the onBlur handling in favor of onchange, but KEEPING the onBlur handlers in the component.
The component would write the radio value of the previewed item into the hook form on tab, whatever we had in place at the wrapper level before prevented this for empty values.
This removes the vestigial traces of the blur handling, and assumes we're using change for everything.
I tested most odd interactions I could think of, but please poke around, give it a shot. 
CMDCT-4617
---
Report Creation Modal, 
- Enter name
- Tab through to submit without filling anything out
- You shouldn't be able to submit, good job us.
Measure Details
- Tab through the delivery method question to complete
- the …

[CMDCT-4617] Radio Tab Fix

---

services/ui-src/src/components/modals/AddEditReportModal.tsx
services/ui-src/src/components/modals/Modal.test.tsx
services/ui-src/src/components/modals/Modal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx

When a report is submitted, the name text should be disabled, and the save button should be disabled. The modal still needs to be accessible to see the selected options for admins.
CMDCT-4595
---
https://d2l8l59b4bu011.cloudfront.net/
In Progress reports should behave the same.
Creating new reports should behave the same.
Complete a report and see the above when clicking the edit button. 
---
---

Create New Report Modal read only

---

deployment/stacks/ui.ts

This change will mean that we no longer have issues destroying branches which destroys the stack.
CMDCT-4622
---
The app still works the same.
NA
---
---
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._
---

CMDCT-4622 gets cloudfront logging to stop breaking destroys for ephemeral apps

---

services/app-api/forms/2026/elements.ts
services/app-api/forms/2026/qms.ts
services/app-api/handlers/reports/buildReport.test.ts
services/app-api/handlers/reports/buildReport.ts
services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/app-api/utils/sanitize.ts
services/app-api/utils/tests/sanitize.test.ts

1. We sanitize the body of every request that hits our API, to ensure we never store or even interact with potentially dangerous data.
2. We use the library DOMPurify for this, with a very strict config set to allow through only a limited set of HTML tags.
3. Within our own report templates, we use tags outside of that limited set.
4. As a user completes a report, we store the answers directly in the template. In other words, every time a user saves report data, they are also re-saving the template.
5. Therefore, the first time each report is saved by a user, that report's template is mangled by DOMPurify.
This PR loosens up the DOMPurify config, to allow a slightly broader set of tags, which includes all tags currently in use in our report templates.
In order to verify this is working …

Let things be a little dirtier

---

services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx

Modifying aria-labels for the "Edit Report Name" and "Edit" buttons in the report dashboard to be more specific
CMDCT-4466
---
**Deploy Link:** https://d219no0jteicvi.cloudfront.net/
1. Create a report, and inspect the aria-label "Edit Report Name" and "Edit" buttons. 
2. Confirm that they are now report name specific (e.g. if the report is named abc the aria labels should be "Edit abc report name" and "Edit abc report"
---
---

Better labeling for editing and entering reports

---

services/app-api/utils/bannerValidation.ts
services/app-api/utils/constants.ts
services/app-api/utils/tests/bannerValidation.test.ts
services/ui-src/src/components/fields/DateField.tsx
services/ui-src/src/components/forms/AdminBannerForm.test.tsx
services/ui-src/src/constants.ts
services/ui-src/src/utils/other/time.test.ts
services/ui-src/src/utils/other/time.ts
services/ui-src/src/utils/validation/bannerValidation.test.ts
services/ui-src/src/utils/validation/bannerValidation.ts

There is a lot of yup validation here -- as Angela suggested. 
After Ben's awesome re-factor, typing the date correctly was possible!
Note: Dates are so weirrddddd. We go from `string` to `number` to "Date" to "ET" to "Utc" to `epoch` to `eons` to `galaxy years` to `1970` because 1970 is when time started - I'm just kidding - I'm exaggerating here.
Here's some context for some of the yup updates:
* yup quirk: `startDate` is passed into the custom validation function as a singleton array, instead of just its actual value. Thanks Ben for adding the code that => `always expects startDate to be an array with one number in it and the test for that on the frontend`
* `schema.test({...})` defines a custom validation rule for the endDate field, ensuring that if both startDate and endDate are …

[HCBS] - Make sure start date is before end date in banner form

---

.github/setBranchName.sh
.github/workflows/dependabot-auto-merge.yml
.github/workflows/deploy.yml

Undo the removal of dependabot:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/507/files
This PR reenables the following:
- Branch names for dependabot are converted to an md5sum and shortened
- Dependabot branches deploy
- Dependabot branches auto-merge assuming required checks pass
CMDCT-4379
---
Once this is merged, monitor future PRs
---
---

Enable dependabot & automerge on success

---

services/ui-src/src/components/fields/RadioField.test.tsx
services/ui-src/src/components/fields/RadioField.tsx

- Added confirmation modal to "Measure Delivery Methods" radio selection
- Added tests for the above
CMDCT-4679
---
Testing link: https://d32vy2hunqr1jq.cloudfront.net/
- Create a new QMS report
- Go to edit LTSS-1 
- Under "Measure Delivery Methods" try changing the radio buttons and verify the following
- If no radio buttons were selected, can select an option as normal
- If a radio is already selected, trying to change it will show a modal with a warning
- Clicking "Yes" confirms and changes the radio value
- Clicking "No" keeps the current value
---
---

CMDCT-4679 - Delivery Methods confirmation modal

---

services/app-api/forms/2026/qms/measureTemplates.ts

UAT testing was done and it was found that MLTSS was not loading properly.
This PR covers correcting the id for MLTSS for POM-2, it' previously was mislabeled and was causing funky errors such as it not showing up when you click on that measure - which makes total sense considering the id was wrong.
CMDCT-4273
---
**Deploy Link:** https://d59261nijki1b.cloudfront.net/
1. Login as a state user
2. When creating a report, select yes for POMS
3. Navigate to required measures
4. Select POM: People Participate in the Life of the Community
5. Confirm bugs no longer exist
---
---

QMS - UAT - POM: People Participate in the Life of the Community Bug Fix

---

services/ui-src/src/components/fields/RadioField.test.tsx
services/ui-src/src/components/fields/RadioField.tsx

- Calling to update zustand state again with proper data in case of `qmDeliveryMethodChange`
More detail: While `setAnswers()` is already being called on every change inside `ReportPageWrapper.tsx`, because we are showing a modal to the user before we actually make the switch, the `setAnswers()` is being called without any change. Now in these cases we will call `setAnswers()` again from inside `RadioField.tsx` with the 
CMDCT-4799
---
- Login: https://d2uf3a1nswxoll.cloudfront.net/
- Navigate to LTSS-1
- For Measure Delivery Methods, select an initial radio selection, and refresh to make sure it saved
- Select a different radio selection, confirm on the modal, then refresh. Make sure the radio selection persists
---
---
_convert to a different template: [test → …

in radio modal case qmDeliveryMethodChange, update state again

---

services/ui-src/src/components/modals/AddEditReportModal.test.tsx
services/ui-src/src/components/modals/AddEditReportModal.tsx
services/ui-src/src/components/modals/AddFormOptions/CiOptions.tsx
services/ui-src/src/components/modals/AddFormOptions/QmsOptions.tsx

- Modified `AddEditReportModal.tsx` to be able to provide variable `topText` and `yearHelperText` per report (currently only the QMS report needs them
- Modified the CI report verbiage
CMDCT-4741
---
- Login: https://dvsfspmlgpvt9.cloudfront.net/
- Click "Enter CI Report online" -> "Start Critical Incident Report"
- Verify that the verbiage matches the story
- Go through the same flow for QMS and verify all the verbiage there is the same as to what it is today
---
---

CMDCT-4741 - add report modal ci updates

---

services/ui-src/src/components/app/AppRoutes.tsx
services/ui-src/src/components/component-inventory/ComponentInventory.tsx
services/ui-src/src/components/component-inventory/elementObject.tsx
services/ui-src/src/components/fields/index.tsx
services/ui-src/src/components/index.ts

This is a very rough draft for the spike for creating a component inventory page. 
Many of the elements depending on report details would require more in depth work.
This lists out the most basic components while showing a "No example available for this component." message for the ones not yet available.
CMDCT-4667
New Branch created for new PR - [last one](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/314) was failing.
---
**Deploy Link:** https://d1gzyt2auyfbet.cloudfront.net/
1. Login in as stateuser@test.com
2. Go to url at top and add "/component-inventory" to view this page
Note: Next step would be adding a feature-flag and maybe a button to click to go to this view

[HCBS] Component Inventory Page - RETRY

---

services/ui-src/src/utils/state/reportLogic/reportActions.test.ts
services/ui-src/src/utils/state/reportLogic/reportActions.ts

This should address [the issue Rocio noted](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/321#pullrequestreview-3073369325) on #321. Specifically: tabbing through a completed measure page, without changing any values, puts the measure back into "In Progress" status.
It was caused because several report components call their `onChange` handler on blur. This resulted in a store action, which assumed that the values had changed, and therefore changed the page status.
I still believe that calling onChange within those components is a good idea; it's a really neat way to make sure that the validation/error message is up-to-date without writing any additional code. Which leaves two options: Either make every component's onChange handler smart enough to not call `updateElement` unless …

Prevent no-op "updates" from resetting measure status

---

services/app-api/forms/2026/elements.ts
services/ui-src/src/components/export/ExportedReportWrapper.test.tsx
services/ui-src/src/components/export/ExportedReportWrapper.tsx
services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
services/ui-src/src/components/pages/Export/ExportedReportPage.tsx

- PDF view will now filter out empty optional measures, sections, and elements
- Note: There will be a future story that will add the "required: false" to any element thats currently not labeled (and should be false).
CMDCT-4836
---
- Login: https://d3e7j0jha4u8as.cloudfront.net/
- Create a new QMS report
- In first required measure LTSS-1 fill out the "Additional notes" textArea, select one of the "Measure Delivery Methods" and fill out a part of the delivery method
- Go back and into the first Optional Measure FASI-1, fill out same things as the point above
- Go to submit page and click to Review PDF.
- Verify that you can only see the Additional Comment that are filled out, measure delivery methods that are started, and optional measures that are started
---
---
_convert to a different …

CMDCT-4836 - PDF - Filter out Optional Fields/Not Started Optional Measures

---

services/ui-src/src/components/app/AppRoutes.tsx

This PR handles taking the steps to add the component inventory page under a feature flag
"componentInventory" LD Flag has been added by @BearHanded via LaunchDarkly - enabled in Dev only and disabled in val and prod.
CMDCT-5016
---
Once merged, we can test that it's in Dev and not Val or Prod

[HCBS] Component Inventory Page - Feature Flag

---

services/ui-src/src/components/app/App.tsx

While testing with BlaxtX, we noticed Tealium wasn't firing. 
Tealium code in the App file was commented out. 
This change should ensure it shows up correct in dev.
Once merged, I will confirm before tomorrow's re-check with Arturo and Daniel from BlastX.
CMDCT-5066

[HCBS] Tealium in App file

---

deployment/stacks/api.ts
services/app-api/utils/kafka/kafka-source-lib.test.ts
services/app-api/utils/kafka/kafka-source-lib.ts

CMDCT-5253: Replace all instances of BOOTSTRAP_BROKER_STRING_TLS with brokerString
CMDCT-5253
---
---
---
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._
---

CMDCT-5253: Replace all instances of BOOTSTRAP_BROKER_STRING_TLS with brokerString
