Enterprise-CMCS/macpro-mdct-hcbs

- src/run.ts
> Disable delete topics until we have topics

- services/ui-src/src/components/accordions/TemplateCardAccordion.test.tsx
- services/ui-src/src/components/accordions/TemplateCardAccordion.tsx
- services/ui-src/src/components/app/AppRoutes.tsx
- services/ui-src/src/components/cards/TemplateCard.test.tsx
- services/ui-src/src/components/cards/TemplateCard.tsx
- services/ui-src/src/components/index.ts
- services/ui-src/src/components/layout/HomePage.tsx
- services/ui-src/src/components/tables/Table.test.tsx
- services/ui-src/src/components/tables/Table.tsx
- services/ui-src/src/constants.ts
- services/ui-src/src/types/other.ts
- services/ui-src/src/utils/api/requestMethods/getRequestHeaders.ts
- services/ui-src/src/utils/api/requestMethods/getTemplateUrl.test.ts
- services/ui-src/src/utils/api/requestMethods/getTemplateUrl.ts
- services/ui-src/src/utils/auth/UserProvider.tsx
- services/ui-src/src/utils/index.ts
- services/ui-src/src/verbiage/pages/home.ts
- src/run.ts
Provide the Landing Page with the first Report explanation and link.
Give the user something to see on login.
CMDCT-3760
---
1. Login with stateuser@test.com credentials
2. This will immediately show the Home Page with a tentative design pending more information and assets.
N/A
---
---
> HCBS Landing Page

- services/ui-auth/libs/users.json
- services/ui-src/src/types/users.ts
- services/ui-src/src/utils/auth/UserProvider.tsx
Provided role names were misformatted, correcting them from `mdct-hcbs-...` to `mdcthcbs`. The rest of the provided name syntax was correct.
CMDCT-3827
---
Deployed env can be logged into with any role.
https://d2mz598fhz5r45.cloudfront.net/
---
---
> Remove dash in idm role name

- services/app-api/forms/qm.ts
- services/app-api/types/reports.ts
- services/ui-src/src/components/report/Elements.tsx
- services/ui-src/src/components/report/Page.tsx
- services/ui-src/src/components/report/ReportPageWrapper.tsx
- services/ui-src/src/components/report/StatusTable.test.tsx
- services/ui-src/src/components/report/StatusTable.tsx
- services/ui-src/src/types/report.ts
- Match [Figma](https://www.figma.com/design/B8IEoYKQ7DuQyx5nStls8F/HCBS?node-id=28-17614&t=oPNYin11gXNkYYAO-4) (Design Review) ✅ 
- Root pages appear as complete
- Hold on Submit until we clarify submission rules
- PDF Button links to a placeholder PDF page. This should be outside the report structure with the same URL params
- Edit links take you to sections in navbar
- Code coverage for this PR: 88.2% for lines 42-55 as that's the TO-DO logic for when we update the status icons
| Nav Bar | Review & Submit Page | 
| ----- | ----- |
| <img width="600" alt="Quality Measures Report Nav Bar " src="https://github.com/user-attachments/assets/edee4335-1afb-4010-acde-52f239625c45"> | <img width="600" alt="Review & Submit Page" src="https://github.com/user-attachments/assets/f7aa4e76-cfa2-4a51-a2 …
> [HCBS] Submit Report Page

- services/app-api/forms/qm.ts
- services/app-api/types/reports.ts
- services/ui-src/src/components/report/MeasureTable.tsx
- services/ui-src/src/types/report.ts
CMDCT-4136
---
1. Log in as any user
2. Go to QM report and start a new one
3. Go to Required Measure Results tab
4. Make sure that the page tab matches the [figma](https://www.figma.com/design/B8IEoYKQ7DuQyx5nStls8F/HCBS?node-id=787-11139&t=z5vcrRQNrkO5Rhul-0)
> CMDCT-4136: adding measures to required measures page

- services/app-api/forms/qm.ts
- services/ui-src/src/components/report/MeasureTable.tsx
This is the fix to a trailing TO-DO based on [Routing By Page Id](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/54) and [setting up](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/66) the measures, AND including the ONE and ONLY quality measure (MLTSS) for LTSS-5 at the bottom of the page. 
Prior to this fix: cmit wasn't being set, therefore the Quality Measures was showing up empty even though previously we did have those showing up.
CMDCT-4147 (kinda)
---
**Cloudfront URL: https://d35uyj0spo417i.cloudfront.net/**
1. Sign into HCBS, any state user
2. Create a QM report
3. On the sidebar menu, select [Optional Measure Results]. 
- The 6th row down will be LTSS-5, CMIT #1255.
4. Click [Edit] and you be taken to the LTSS-5 measure overview page.
5. Check that the …
> [HCBS] QMS - Set CMIT Number & Add QM to LTSS-5

- services/app-api/handlers/reports/submit.test.ts
- services/app-api/handlers/reports/submit.ts
- services/app-api/serverless.yml
- services/ui-src/src/components/report/StatusTable.test.tsx
- services/ui-src/src/components/report/StatusTable.tsx
- services/ui-src/src/utils/api/requestMethods/report.test.ts
- services/ui-src/src/utils/api/requestMethods/report.ts
CMDCT-4093
---
Right now there is no UI that will indicate a report has been submitted. Instead, run this PR locally and confirm in your terminal that the submit endpoint was called 
e.g.
---
---
> [HCBS] Submit Report

- services/app-api/serverless.yml
Refer to this one: https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/97
> CMDCT-4243 - region quirk fixed

- services/ui/serverless.yml
Makes sure that all s3 buckets have no public access and are versionsed
CMDCT-4303
---
NA
---
---
> CMDCT-4303 - adds correct s3 config

- run
- services/ui/serverless.yml
- src/run.ts
- src/slsV4BucketPolicies.ts
CMDCT-4302 & CMDCT-4309 - UI Bucket should not be a website in S3 and enforce SSL on Serverless Buckets
CMDCT-4302
CMDCT-4309
---
---
---
> CMDCT-4302 & CMDCT-4309 - UI Bucket should not be a website in S3 and enforce SSL on Serverless Buckets

- services/database/serverless.yml
We're required to enlist the app in CPM, which requires tags on the tables to be seen when scanned. We will start with the no backup option, and discuss with the group to see what levels are required, but this will get us in the system and satisfy the onboarding process.
N/A
---
Tag should be visible on the created dynamo table
---
---
> Add Placeholder CPM Tag

- services/app-api/handlers/reports/buildReport.ts
- services/app-api/types/reports.ts
- services/app-api/utils/reportValidation.ts
- services/ui-src/src/components/fields/DropdownField.test.tsx
- services/ui-src/src/components/fields/DropdownField.tsx
- services/ui-src/src/components/fields/RadioField.tsx
- services/ui-src/src/components/fields/TextAreaField.test.tsx
- services/ui-src/src/components/fields/TextAreaField.tsx
- services/ui-src/src/components/fields/TextField.test.tsx
- services/ui-src/src/components/fields/TextField.tsx
- services/ui-src/src/components/index.ts
- services/ui-src/src/components/modals/AddEditReportModal.test.tsx
- services/ui-src/src/components/modals/AddEditReportModal.tsx
- services/ui-src/src/components/report/Page.test.tsx
- services/ui-src/src/components/report/Page.tsx
- services/ui-src/src/types/report.ts
Creates a dropdown component file, and replaced the dropdown in AddEditReportModal.tsx with the component.
Nothing has visually changed.
CMDCT-4255
---
Deploy Link: https://d3j4cgp0za0lud.cloudfront.net/
2) Create a new QMS report
3) If there's no issues creating the report than everything is good.
---
---
> Create custom DropdownField

- services/app-api/forms/defaultMeasures.ts
- services/app-api/forms/pomMeasures.ts
- services/app-api/handlers/reports/buildReport.ts
- services/app-api/types/reports.ts
- services/app-api/utils/reportValidation.ts
- services/ui-src/src/components/index.ts
- services/ui-src/src/components/report/MeasureDetails.tsx
- services/ui-src/src/components/report/Page.test.tsx
- services/ui-src/src/components/report/Page.tsx
- services/ui-src/src/styles/theme.ts
- services/ui-src/src/types/report.ts
This PR adds the Measure Details section at the top as a page element. 
To match [figma](https://www.figma.com/design/B8IEoYKQ7DuQyx5nStls8F/HCBS?node-id=1926-31107&t=Bdd7bhZ9zn6LT1W1-1):
- Measure name, cmit #, steward & collection method appear at the top of each measure information page
- a divider was added
- updated the title for the next section to **Measure Information* to avoid confusion as it was previously **Measure Details**
- Bonus updates (FIGMA MATCHING): 
- updated "Textbox" to "TextAreaField" for defaultMeasures question: 
`Please explain the variance.` for consistency across measure pages/match Figma.
- updated radio answers and sub question for "Were the reported measure results audited or validated?" (These changes already exist for pomMeasures but not for …
> HCBS - Measure Details Section

- services/database/serverless.yml
Setting up tag based rules for AWS Backup. These are configured in Backup plan to conform with CMS guidance. The backup plan is named and tagged inline with their expectations.
This pull request just conforms with the expected tag format to be picked up, and the 35 day policy matches the prior policy in other MDCT Apps.
N/A
---
Tags exist on dynamo db table after deployment
---
---
> AWS Backup tag

- services/ui-src/src/components/fields/RadioField.tsx
- services/ui-src/src/components/fields/ReportingRadioField.tsx
Quick PR to fix bug in hide elements functionality
I also fixed radio button error display. Errors were not bubbling up. This is currently untestable because validation has been turned off so no need to test.
https://d2jibfd6np8f8d.cloudfront.net/
1. Log in as any state user, create or edit a report and go to one of the following required measures: LTSS-6, LTSS-7, LTSS-8
2. Fill out the form. Notice that as you toggle between "yes" and "no" on the "Is the state reporting on this measure?" question, "no" will hide all the elements and "yes" will bring them back
3. Test out various configurations of the form, like fill out a bunch of stuff when "yes" is selected, toggle to "no" so the elements all go away, and then toggle "yes" to bring back and make sure all the questions come back with …
> [NO TICKET]: fixing issue with hide elements functionality 

- services/ui-src/src/components/report/MeasureClearModal.test.tsx
- services/ui-src/src/components/report/MeasureClearModal.tsx
- services/ui-src/src/components/report/MeasureFooter.tsx
Quick fix for the footer that stopped rendering on child pages. Bad copy paste of behavior on the selector branch that expected a MeasureTemplate behavior, but should be able to realistically handle any page type.
N/A
---
Create a report, all relevant pages should see the footer
---
---
> Fix footer not rendering

- services/ui-src/src/components/forms/AdminDashSelector.test.tsx
- services/ui-src/src/components/forms/AdminDashSelector.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
CMDCT-4429
---
cloudfront: https://d3d7no8lxmvpzw.cloudfront.net/
Login as an admin, and confirm a few content changes (on the landing page and the dashboard page): 
Figma link: [Link](https://www.figma.com/design/B8IEoYKQ7DuQyx5nStls8F/HCBS?node-id=726-15597&t=3OzAj8BRN1T4B2dH-1)
---
---
> [HCBS] Admin - Landing Page

- services/app-api/handlers/reports/buildReport.ts
- services/app-api/handlers/reports/submit.ts
- services/app-api/types/reports.ts
- services/app-api/utils/reportValidation.ts
- services/app-api/utils/tests/mockReport.ts
- services/app-api/yarn.lock
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
- services/ui-src/src/components/report/ReportPageWrapper.test.tsx
- services/ui-src/src/types/report.ts
- services/ui-src/src/utils/state/management/reportState.test.ts
- services/ui-src/src/utils/testing/setupJest.tsx
Adds tracking for submission count, and archival, renders them, but does not fix styles. Styles will come before the ticket finishes but this unblocks the other 2 tickets.
Centralizes the logic from roles in the table to the defined behavior by column.
View per role - 
State:
Help Desk:
Admin: 
CMDCT-4430
---
https://d2ufbmtclylfk.cloudfront.net/
Log in as state user
Create report
Submit a report (note the ui for that just leaves you sitting idly)
Log in as admin
Dashboard should display the submission count as well as new buttons that don't work!
---
---
> [CMDCT-4430] Admin Dashboard buttons with no styling

- tests/playwright.config.ts
- tests/playwright/stateuser.spec.ts
CMDCT-4433
---
confirm all tests are passing and the integration test makes sense
---
---
> [HCBS] Integration Test: Create QMS Report

- services/app-api/forms/2026/measureTemplates.ts
Added anything missing from the delivery method page for MLTSS
CMDCT-4384
---
The only thing missing from the MLTSS delivery method page was the instructions accordion and performance rates section. Confirm that it is present and looks like below
---
---
> [HCBS] - QMS - MLTSS: Plan All-Cause Readmission Details Page

- services/app-api/forms/2026/elements.ts
- services/app-api/forms/2026/measureTemplates.ts
So long 
CMDCT-3533
---
Reports should generate without strat headers or questions
---
---
> [CMDCT-3533] Remove all stratification elements

- services/app-api/forms/2026/elements.ts
- services/ui-src/src/components/rates/types/Fields.test.tsx
- services/ui-src/src/components/rates/types/Fields.tsx
- services/ui-src/src/components/rates/types/NDR.test.tsx
- services/ui-src/src/components/rates/types/NDR.tsx
- services/ui-src/src/components/rates/types/NDREnhanced.test.tsx
- services/ui-src/src/components/rates/types/NDREnhanced.tsx
- services/ui-src/src/components/rates/types/NDRFields.test.tsx
- services/ui-src/src/components/rates/types/NDRFields.tsx
- services/ui-src/src/components/report/PerformanceRate.test.tsx
- services/ui-src/src/components/report/PerformanceRate.tsx
Simple text replace update.
Current year = 2026
Rates = current year + 2
https://jiraent.cms.gov/browse/CMDCT-4539
---
---
---
> [CMDCT-4539] Year text

- services/app-api/forms/2026/qms.ts
- services/app-api/forms/2026/templates.test.ts
- services/app-api/handlers/reports/release.ts
- services/app-api/handlers/reports/submit.ts
- services/app-api/types/reports.ts
- services/app-api/utils/reportValidation.ts
- services/app-api/utils/tests/mockReport.ts
- services/app-api/utils/tests/reportValidation.test.ts
- services/ui-src/src/components/export/ExportedReportWrapper.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/components/report/Elements.tsx
- services/ui-src/src/components/report/MeasureFooter.tsx
- services/ui-src/src/components/report/Page.test.tsx
- services/ui-src/src/components/report/Page.tsx
- services/ui-src/src/components/report/ReportPageWrapper.tsx
- services/ui-src/src/components/report/StatusAlert.test.tsx
- services/ui-src/src/components/report/StatusAlert.tsx
- services/ui-src/src/components/report/StatusTable.test.tsx
- services/ui-src/src/components/report/StatusTable.tsx
- services/ui-src/src/components/report/SubmissionParagraph.test.tsx
- services/ui-src/src/components/report/SubmissionParagraph.tsx
- services/ui-src/src/styles/theme.ts
- services/ui-src/src/types/report.ts
- services/ui-src/src/utils/state/selectors.test.ts
- services/ui-src/src/utils/state/selectors.ts
- services/ui-src/src/utils/testing/setupJest.tsx
- services/ui-src/src/utils/validation/reportValidation.test.ts
A new view!
Also includes extra submission metrics, and the logic for the alert on the submit page pre-submission.
CMDCT-4516
---
Deploy Link: https://dg2wvauwfkzwt.cloudfront.net/
- Start a report
- Don't include pom for speed
- On the submit page there should be an error banner
- fill out all sections that are required
- On the submit page the banner is gone
- Submit!
- There should now be a nice view thanking you for what you've done
---
---
> Submit view

- services/app-api/forms/2026/elements.ts
- services/ui-src/src/components/rates/calculations.tsx
- services/ui-src/src/components/rates/types/Fields.test.tsx
LTSS-8 was using ltss-7 calcs without the same ids. Unify
CMDCT-4540
---
https://d2bw1k1coveg7k.cloudfront.net/
LTSS-7 & 8 rates work
---
---
> fix ltss-7/8 conflict in ids

- deployment/deployment-config.ts
- deployment/local/prerequisites.ts
- src/run.ts
Quick patch to CMDCT-4391 to get local setup working again
> CMDCT-4391 - adds in working local setup

- services/app-api/forms/2026/elements.ts
Added warning text to Measure Delivery Method sections
CMDCT-4547
---
Confirm that the warning text shows up (is gray instead of yellow)
---
---
> Measure Delivery Method warning text

- src/run.ts
Reorders destroy stuff to keep it from failing
CMDCT-4590
---
NA github actions will do the magic
---
---
> CMDCT-4590 fixes destroy failures

- services/ui-src/src/components/modals/AddEditReportModal.test.tsx
- services/ui-src/src/components/modals/AddEditReportModal.tsx
Content changes
CMDCT-4559
---
Check against [document](https://docs.google.com/document/d/1XbVZ8_7TLEtSB8JQeDK8W6WJdkoJLSHz/edit#heading=h.2s8eyo1) and confirm that content matches
---
---
> QMS Content Update - Create Report Modal

- services/app-api/forms/2026/qms.ts
Content changes
CMDCT-4560
---
Check against [document](https://docs.google.com/document/d/1XbVZ8_7TLEtSB8JQeDK8W6WJdkoJLSHz/edit#heading=h.7twnlrsedaxd) and confirm that content matches
---
---
> QMS Content Update - General Information

- services/ui-src/src/components/export/ExportedReportWrapper.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
Adds a little checkbox to the pdf page that shows all the hidden elements, and their types. Small development tool for ideating on pdf with design to get us talking the same language. To be removed in the future.
Dear Aileen, a checkbox is the right input element.
N/A
---
Go to the pdf page, and click this button a bunch.
---
---
> PDF Debug Button

- services/ui-src/src/components/cards/QMSIntroductionCard.test.tsx
- services/ui-src/src/components/cards/QmsIntroductionCard.tsx
- services/ui-src/src/components/cards/ReportIntroCard.test.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
Content changes per ticket.
**Note: Title has been corrected from screenshot**
CMDCT-4557, CMDCT-4558
---
https://d2d2ermvegizla.cloudfront.net/
---
---
> [CMDCT-4557] Content Update - Intro page

- services/app-api/forms/2026/qms.ts
Content changes
CMDCT-4561
---
Check against [document](https://docs.google.com/document/d/1XbVZ8_7TLEtSB8JQeDK8W6WJdkoJLSHz/edit#heading=h.nlf6ps3rngxz) and confirm that content matches
---
---
> QMS Content Update - Required Measures Page

- services/app-api/forms/2026/elements.ts
- services/app-api/forms/2026/measureTemplates.ts
Looks like I missed added the complete banner to the child sections of the pom measures. This pr adds them back.
---
Deploy Link: https://d16w6rd40fji55.cloudfront.net/
---
---
> POM Child Complete Banner

- .env.tpl
- deployment/stacks/data.ts
- services/app-api/forms/yearlyFormSelection.ts
- services/app-api/handlers/kafka/post/postKafkaData.ts
- services/app-api/storage/reports.ts
- services/app-api/testing/setupJest.ts
- services/app-api/types/reports.ts
- services/app-api/utils/constants.ts
- services/topics/handlers/createTopics.js
- tests/playwright/stateuser.spec.ts
Adds the TA & CI tables.
Coverage will follow as code uses these portions in upcoming tickets.
Tables created on ephem branch and topics created.
Bonus: Include playwright test button fix
CMDCT-4609
---
The screenshots above display functionality, but you can additionally confirm them by:
AWS - DynamoDB, the tables should exist.
CreateTopics lambda - Topics to be created are logged.
---
---
> [CMDCT-4609] TA & CI tables

- .github/workflows/delete-pages.yml
- removeOldFolders.js
Quick follow up to this one:
https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/pull/261
> adds removeOldFolders.js to main

- deployment/constructs/dynamodb-table.ts
Tag is important and was removed during CDK conversion
CMDCT-4669
---
Make sure app still works
NA
---
---
> CMDCT-4669 adds back missing tag to dynamo tables

- services/ui-src/src/components/layout/Header.tsx
- Main header goes from sticky to static at 200% zoom and greater
CMDCT-4449
---
- Testing link: https://dfie2xtjj7b.cloudfront.net/
- Verify header is sticky at 100% zoom
- Verify header is static at 200% zoom and above
---
- [] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary
---
> CMDCT-4449 - make header static at 200 zoom

- services/app-api/forms/2026/ci/ci.ts
- services/app-api/forms/2026/ta/ta.ts
- Added new optional question to TA report
- Fixed wrong type casing for the CA report
CMDCT-4648
---
- Create new TA report -> observe the new question on the general page
- Testing env: https://d29p46fa2hfe52.cloudfront.net/
---
---
> CMDCT-4648 - added programs question to TA report

- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- .github/workflows/update-code-json.yml
- code.json
ShareIT compliance is required
CMDCT-4692
---
See that this worked:
https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/actions/runs/15304931888/job/43055064139
Also feel free to check out code.json in the project root now.
NA
---
---
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._
---
> CMDCT-4692 ShareIT compliance

- services/app-api/forms/2026/qms/measureTemplates.ts
- services/app-api/forms/2026/qms/qms.ts
- services/app-api/types/reports.ts
- services/app-api/utils/reportValidation.ts
- services/app-api/utils/tests/reportValidation.test.ts
- services/app-api/utils/tests/sanitize.test.ts
- services/ui-src/index.html
- services/ui-src/src/components/layout/HomePage.tsx
- services/ui-src/src/components/modals/AddEditReportModal.test.tsx
- services/ui-src/src/components/modals/AddFormOptions/QmsOptions.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
- services/ui-src/src/components/pages/HelpPage/HelpPage.test.tsx
- services/ui-src/src/components/pages/HelpPage/HelpPage.tsx
- services/ui-src/src/components/rates/calculations.tsx
- services/ui-src/src/types/report.ts
- services/ui-src/src/utils/state/reportLogic/reportActions.ts
- tests/playwright/stateuser.spec.ts
- tests/playwright/utils/auth.setup.ts
Content updates across QMS
CMDCT-4677
---
cloudfront link: https://d17p3b0qnoalya.cloudfront.net/
A few different content updates here: 
1. Report Creation Modal
- Update HCI-IDD beneficiary survey to be "NCI-IDD"
- Remove the word "beneficiary" from each survey.
2. Landing Page
- Remove the sentence and link:  Learn more about this new data collection tool from CMS
**(this text should not exist anymore)**
3. Reports Landing Page
- In the instructional texts, case should be sentence case for the status names:
- Not Started > Not started
- In Progress > In progress
- In Revision > In revision
4. FASI-2 Measure Details sections
- Performance Rate for FASI-2 should be: Participant whose Person-Centered Service Plan Documentation Addresses Needs in the Areas of Self-Care, Mobility, and IADL …
> QMS - UAT - Content Updates

- services/app-api/forms/2026/elements.ts
- services/app-api/forms/2026/qms/measureTemplates.ts
- services/ui-src/src/components/rates/types/NDREnhanced.test.tsx
- services/ui-src/src/components/rates/types/NDREnhanced.tsx
- Modified `NDREnhanced` to remove/add the trailing s where needed
- Added new label verbiage in cases of exclusion rates
CMDCT-4719
---
- Login: https://dyt4a0syzn8yo.cloudfront.net/
- Create a new QMS report
- Verify the exclusion rate language on the following measures:
LTSS-1
LTSS-2
LTSS-3
LTSS-4
LTSS-5
---
---
> CMDCT-4719 - fix exclusion rate wording

- services/ui-src/src/components/cards/CiIntroductionCard.test.tsx
- services/ui-src/src/components/cards/CiIntroductionCard.tsx
CMDCT-4739
---
- Login: https://d14iapityd9n3t.cloudfront.net/
- On the landing page verify the Critical Incident card matches the wording of the story
---
---
> CMDCT-4739 - critical incident card wording

- services/app-api/forms/2026/ci/ci.ts
- Added needed text area to CI Report General Info Page
CMDCT-4742
---
- Login: https://d1b6t1vdqtfong.cloudfront.net/
- Create new CI report
- Verify wording/elements match the story
---
---
> CMDCT-4742 - CI report general info page

- deployment/constructs/lambda-dynamo-event.ts
- deployment/constructs/lambda.ts
- deployment/stacks/ui-auth.ts
add forceDockerBundling to esbuild bundling
CMDCT-
---
---
---
> add forceDockerBundling to esbuild bundling

- services/app-api/forms/2026/ci/ci.ts
- services/app-api/forms/2026/elements.ts
- services/app-api/types/reports.ts
- services/app-api/utils/reportValidation.ts
- services/ui-src/src/components/rates/types/NDRBasic.test.tsx
- services/ui-src/src/components/rates/types/NDRBasic.tsx
- services/ui-src/src/types/report.ts
- Modified `NDRBasic` to accept minimum required rate and show alerts based on the calculated rate
- Added all required fields for HCBS INCID-1, 2, and 3
- Fixed a couple of spacing/spelling mistakes I found
CMDCT-4744
CMDCT-4745
CMDCT-4746
CMDCT-4747
CMDCT-4748
---
- Login: https://dmobvnmmbhace.cloudfront.net/
- Create a new CI report
- Verify the verbiage matches the stories/content doc across HCBS INCID-1, 2, and 3
- Verify that after you enter a numerator and denominator, an appropriate alerts shows
---
---
> CMDCT-4744-4748 - CI Report Measures

- services/ui-src/src/components/export/ExportedReportBanner.tsx
- services/ui-src/src/components/export/ExportedReportElements.test.tsx
- services/ui-src/src/components/export/ExportedReportElements.tsx
- services/ui-src/src/components/export/ExportedReportTable.tsx
- services/ui-src/src/components/export/ExportedReportWrapper.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/components/report/MeasureDetails.tsx
- services/ui-src/src/styles/components/table.ts
- services/ui-src/src/types/report.ts
- services/ui-src/src/utils/other/arrays.test.ts
- services/ui-src/src/utils/other/arrays.ts
This PR is for adding the Table components into the PDF, it also kickstarts the structure we want to use when rendering new components on the page.
https://github.com/user-attachments/assets/dfc470a6-31fb-4858-b079-ad4f235fbd41
**So What Are These Files?**
1) ExportedReportElements.tsx - Is similar to Page.tsx and where you would add renders for components that aren't part of the table or needs a unique table like performance measure components.
2) ExportedReportTable.tsx - This is the Indicator / Response table made reusable.
**Question for Y'all**
Would folks prefer to have export renders in the same file as the component being rendered? Example:
or to have it all in the ExportedReportElements.tsx file itself
**Notes:** 
1) I didn't read the ticket at first and thought I was suppose to …
> [CDMCT-4831] Create PDF Table Components

- deployment/constructs/dynamodb-table.ts
- deployment/constructs/lambda-dynamo-event.ts
- deployment/constructs/lambda.ts
- deployment/constructs/waf.ts
Update HCBS to manage log groups and update CDK constructs
CMDCT-4976
---
Open deployed instance and confirm it works https://dp3ckw9mwh6qu.cloudfront.net/
---
---
> Update HCBS to manage log groups and update CDK constructs

- services/app-api/forms/2026/elements.ts
This PR covers a tiny content update to LTSS rates.
All 3 Rates: Change "Minimizing Length of Facility Stay"  to "Successful Transition after Long-Term Facility Stay"
CMDCT-5063
**Deploy Link:** https://d1htg830fmk7wc.cloudfront.net/
1. Create a new report for `QMS`
2. Go to `LTSS-8` under `Required Measure Results`
3. Confirm rate content updates in delivery methods: FFS and/or MLTSS
---
---
> [HCBS] QMS - Update Language on LTSS-8

- services/app-api/forms/2026/cmit.ts
- services/app-api/forms/2026/elements.ts
- services/app-api/forms/2026/qms/measureOptions.ts
- services/app-api/forms/2026/qms/measureTemplates.ts
- services/app-api/types/reports.ts
- services/ui-src/src/components/rates/types/Fields.test.tsx
- services/ui-src/src/components/rates/types/NDR.test.tsx
- services/ui-src/src/components/rates/types/NDREnhanced.test.tsx
- services/ui-src/src/components/report/MeasureResultsNavigationTable.tsx
- services/ui-src/src/types/report.ts
- services/ui-src/src/utils/testing/mockRates.tsx
- tests/playwright/reports/qms.spec.ts
- tests/playwright/utils/measureUtils.ts
* Update all mentions of "LTSS-5" to "MLTSS-5": CMDCT-5168
* Replace "the 2026 technical specifications" with "the most current technical specifications", in all measures: CMDCT-5169
* Make the waiver/demonstration question required: CMDCT-5170
* Remove "for this assessment" from the performance target question: CMDCT-5171
+ Except for LTSS-6 and HCBS-10, which use the NDRFields component to create a more specific wording
See above
---
https://d1zc5vouj1p0bm.cloudfront.net/
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
- ~[ ] I have updated relevant documentation, if necessary~
- ~[ ] I have performed a self-review of my code~
---
_If either of the following are true, notify the team's ISSO (Information System Security Officer)._
- ~[ ] These changes …
> QMS Updates, Various

- .github/workflows/scan_security-hub-jira-integration.yml
Doing testing to ensure that this PR will work when these changes go out to all apps:
https://github.com/Enterprise-CMCS/macpro-mdct-core/pull/101
> CMDCT-5230 fixes sechub to jira workflow
